# Generated by Django 3.0.6 on 2020-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
                ('operation', models.CharField(choices=[('in', 'Доход'), ('out', 'Расход')], default='in', max_length=3)),
            ],
            options={
                'verbose_name': 'Финанс',
                'verbose_name_plural': 'Финансы',
            },
        ),
    ]
