# Generated by Django 3.0.6 on 2020-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20200513_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tshirt',
            options={'verbose_name': 'Футболка', 'verbose_name_plural': 'Футболки'},
        ),
        migrations.AddField(
            model_name='tshirt',
            name='title',
            field=models.CharField(default=1, max_length=120, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
