# Generated by Django 3.0.6 on 2020-05-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20200517_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1100, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
