# Generated by Django 3.0.6 on 2020-05-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20200513_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='title',
        ),
    ]
