# Generated by Django 3.0.6 on 2020-05-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.ProductDetail')),
            ],
            options={
                'verbose_name': 'Другой товар',
                'verbose_name_plural': 'Другие товары',
            },
            bases=('finances.productdetail',),
        ),
    ]
