# Generated by Django 3.0.6 on 2020-05-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20200513_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
