# Generated by Django 3.0.6 on 2020-05-18 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_otherdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outerweardetail',
            options={'verbose_name': 'Верхняя Одежда', 'verbose_name_plural': 'Верхняя Одежда'},
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='quantity',
        ),
        migrations.AddField(
            model_name='outerweardetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basefinance',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='finances.Product', verbose_name='Товар'),
        ),
    ]
