# Generated by Django 3.0.6 on 2020-05-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='id',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.Product'),
            preserve_default=False,
        ),
    ]
