# Generated by Django 3.0.6 on 2020-05-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_auto_20200518_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcs', models.CharField(max_length=120, verbose_name='ФИО')),
                ('where', models.CharField(max_length=300, verbose_name='Адрес')),
                ('send_description', models.CharField(max_length=120, verbose_name='Дополнительная Информация')),
                ('send_done', models.BooleanField(default=False, verbose_name='Выполнение')),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='debt_active',
            field=models.BooleanField(default=False, verbose_name='Погашен'),
        ),
    ]
