# Generated by Django 3.0.6 on 2020-05-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20200513_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товар'},
        ),
        migrations.AlterField(
            model_name='basefinance',
            name='operation',
            field=models.CharField(choices=[(True, 'Доход'), (False, 'Расход')], default=True, max_length=3, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='basefinance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.Product', verbose_name='Товар'),
        ),
    ]
