# Generated by Django 3.0.6 on 2020-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20200513_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefinance',
            name='operation',
            field=models.CharField(choices=[('in', 'Доход'), ('out', 'Расход')], default='in', max_length=3, verbose_name='Операция'),
        ),
    ]
