# Generated by Django 3.0.6 on 2020-05-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_auto_20200513_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefinance',
            name='operation',
            field=models.BooleanField(choices=[(True, 'Доход'), (False, 'Расход')]),
        ),
    ]
