# Generated by Django 3.0.6 on 2020-05-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_auto_20200513_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': 'Долг', 'verbose_name_plural': 'Долги'},
        ),
    ]
