# Generated by Django 3.0.6 on 2020-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_auto_20200513_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='basefinance',
            name='operation',
            field=models.BooleanField(choices=[(True, 'Доход'), (False, 'Расход')], verbose_name='Операция'),
        ),
    ]
