# Generated by Django 3.0.6 on 2020-05-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_auto_20200514_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quanity',
        ),
    ]
